name: CI/CD Deployment Pipeline

on:
  workflow_dispatch: # 允許手動觸發

jobs:
  ##################################################
  # 1. BUILD JOB: 建置與打包專案                   #
  ##################################################
  build:
    runs-on: ubuntu-latest
    # 我們不再需要從 job 層級輸出 artifact_name，因為它是一個固定的名稱
    outputs:
      # 保留這個 output，因為後續的 O 級任務需要它
      # 如果您還沒做到 O 級任務，這行可以先忽略
      new_version: ${{ steps.version.outputs.new_version }}
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Run Build Script
        # 假設您已經修正了 package.json 中的 build 指令
        run: npm run build

      - name: 5. Archive Production Artifact
        run: |
          mkdir -p artifact
          cp -r dist artifact/
          cp action.yml artifact/
          cp package.json artifact/
          cp README.md artifact/

      # ✨ --- 修正點 1 --- ✨
      # 直接提供一個固定的 artifact 名稱
      - name: 6. Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: artifact/

  ##################################################
  # 2. DEPLOY TO STAGING JOB: 部署到 Staging 環境   #
  ##################################################
  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      # ✨ --- 修正點 2 --- ✨
      # 使用與上傳時相同的固定名稱來下載
      - name: 1. Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: 2. Create Staging Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          gh release create "$TAG" ./* --title "Staging Release: $TAG" --notes "$NOTE"

  ##################################################
  # 3. DEPLOY TO PRODUCTION JOB: 部署到 Production 環境 #
  ##################################################
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      # ✨ --- 修正點 3 --- ✨
      # 使用與上傳時相同的固定名稱來下載
      - name: 1. Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: 2. Create Production Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          gh release create "$TAG" ./* --title "Production Release: $TAG" --notes "$NOTE"
