name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Update GitHub Activity
        uses: ./ 
        with:
          GITHUB_USERNAME: "kaigiii"
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          EVENT_LIMIT: 10
          README_PATH: README.md
          COMMIT_MESSAGE: "⚡ Update README.md with latest activity"
          
          # ✨ 關鍵修改：忽略可能導致問題的 PushEvent ✨
          IGNORE_EVENTS: "PushEvent"
